import type { Activity } from './types'

/** This term's activity schedule. validFrom/validUntil scope the entries so the
 *  model survives term changes without rewriting logic. */
export const ACTIVITIES: Activity[] = [

  // ── Sarah ──────────────────────────────────────────────────────────────────

  {
    id: 'sarah-fri-idrott',
    personId: 'sarah',
    label: 'Skola: Idrott',
    weekday: 5,
    startTime: null,
    arriveBy: null,
    leaveBy: null,
    endTime: null,
    affectsWindow: false,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: 'dagtid',
  },
  {
    id: 'sarah-fri-hiphop',
    personId: 'sarah',
    label: 'Hiphop t/v nivå 1',
    weekday: 5,
    startTime: '17:30',
    arriveBy: '17:15',
    leaveBy: null,
    endTime: '18:45',
    affectsWindow: true,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: null,
  },
  {
    id: 'sarah-sun-feminine',
    personId: 'sarah',
    label: 'Feminine vibe t/v nivå 2',
    weekday: 7,
    startTime: '12:00',
    arriveBy: '11:45',
    leaveBy: null,
    endTime: '13:30',
    affectsWindow: true,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: 'middag',
  },
  {
    id: 'sarah-sun-jazz',
    personId: 'sarah',
    label: 'Jazz t/v nivå 2',
    weekday: 7,
    startTime: '17:45',
    arriveBy: '17:30',
    leaveBy: null,
    endTime: '19:15',
    affectsWindow: true,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: null,
  },
  {
    id: 'sarah-mon-idrott',
    personId: 'sarah',
    label: 'Skola: Idrott',
    weekday: 1,
    startTime: null,
    arriveBy: null,
    leaveBy: null,
    endTime: null,
    affectsWindow: false,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: 'dagtid',
  },
  {
    id: 'sarah-mon-teater',
    personId: 'sarah',
    label: 'Teater',
    weekday: 1,
    startTime: '18:00',
    arriveBy: null,
    leaveBy: null,
    endTime: '20:00',
    affectsWindow: true,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: 'preliminärt; ingen arrive/leave → startTime gäller som cutoff',
  },
  {
    id: 'sarah-wed-twerk',
    personId: 'sarah',
    label: 'Girly Twerk/Dancehall',
    weekday: 3,
    startTime: '18:45',
    arriveBy: '18:30',
    leaveBy: null,
    endTime: '20:15',
    affectsWindow: true,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: null,
  },

  // ── Annabelle ──────────────────────────────────────────────────────────────

  {
    id: 'annabelle-fri-idrott',
    personId: 'annabelle',
    label: 'Skola: Idrott',
    weekday: 5,
    startTime: null,
    arriveBy: null,
    leaveBy: null,
    endTime: null,
    affectsWindow: false,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: 'dagtid',
  },
  {
    id: 'annabelle-fri-ridning',
    personId: 'annabelle',
    label: 'Ridning',
    weekday: 5,
    startTime: '16:00',
    arriveBy: '15:30',
    leaveBy: null,
    endTime: '17:00',
    affectsWindow: true,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: 'senast 15:30',
  },
  {
    id: 'annabelle-sun-trav',
    personId: 'annabelle',
    label: 'Trav',
    weekday: 7,
    startTime: '14:15',
    arriveBy: null,
    leaveBy: null,
    endTime: '16:15',
    affectsWindow: true,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: 'middag/eftermiddag',
  },
  {
    id: 'annabelle-mon-klarinett',
    personId: 'annabelle',
    label: 'Skola: Klarinett',
    weekday: 1,
    startTime: null,
    arriveBy: null,
    leaveBy: null,
    endTime: null,
    affectsWindow: false,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: 'dagtid',
  },
  {
    id: 'annabelle-mon-idrott',
    personId: 'annabelle',
    label: 'Skola: Idrott',
    weekday: 1,
    startTime: null,
    arriveBy: null,
    leaveBy: null,
    endTime: null,
    affectsWindow: false,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: 'dagtid',
  },
  {
    id: 'annabelle-mon-modern',
    personId: 'annabelle',
    label: 'Modern 10–12',
    weekday: 1,
    startTime: '17:30',
    arriveBy: '17:15',
    leaveBy: null,
    endTime: '18:30',
    affectsWindow: true,
    validFrom: '2026-01-01',
    validUntil: null,
    notes: null,
  },
]
